/* eslint-disable */
// @ts-nocheck
// Generated by Quasar CLI

declare module 'vue' {
  interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $q: import('quasar').QVueGlobals
  }
}

export {}
